package ru.yandex.mishalov.schedule.Server;

public enum Endpoint {
    UNKNOWN,
    GET_TASKS,
    GET_TASKS_ID,
    ADD_TASK,
    DELETE_TASK,
    GET_SUBTASKS,
    GET_SUBTASKS_ID,
    ADD_SUBTASK,
    DELETE_SUBTASK,
    DELETE_ALL_TASKS,
    DELETE_ALL_SUBTASKS,
    UPDATE_TASK,
    UPDATE_SUBTASK,
    GET_EPICS,
    GET_EPIC_ID,
    GET_PRIORITIZED_TASKS,
    ADD_EPIC,
    UPDATE_EPIC,
    DELETE_ALL_EPICS,
    DELETE_EPIC,
    GET_SUBTASKS_EPIC,
    GET_HISTORY

}
